#!/usr/bin/env bash

_aws_azure_login() {
  local -r previous_word=${COMP_WORDS[COMP_CWORD - 1]}
  local -r current_word=${COMP_WORDS[COMP_CWORD]}
  local -a candidates

  case $previous_word in
  --mode)
    candidates=("cli" "gui")
    ;;
  --profile)
    while IFS= read -r line; do
      if [[ $line =~ '[profile '([^]]+)']' ]]; then
        candidates+=("${BASH_REMATCH[1]}")
      fi
    done < "${AWS_CONFIG_FILE:-$HOME/.aws/config}"
    ;;
  *)
    candidates=("--profile" "--configure" "--mode" "--no-sandbox" "--no-prompt" "--enable-chrome-network-service" "--no-verify-ssl" "--enable-chrome-seamless-sso" "-h" "--help")
    ;;
  esac

  COMPREPLY=($(compgen -W "${candidates[*]}" -- "$current_word"))
}

complete -o default -F _aws_azure_login aws-azure-login
